[package]
name = "color-picker"
version = "0.1.0"
edition = "2021"


[dependencies]
slint = "1.14.1"
arboard = "3.2"
rand = "0.8"
palette = "0.7"
clipboard = "0.5"

[build-dependencies]
slint-build = "1.14.1"
